# Generated by Django 4.1.3 on 2023-01-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_quizmaster',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_quiztaker',
        ),
    ]
